name: Update Version and Release

on:
  push:
    tags:
      - '*'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 关键！必须获取完整历史

      - name: Update version constant
        run: |
          TAG_NAME=${{ github.ref_name }}
          sed -i "s/const Version = \".*\"/const Version = \"$TAG_NAME\"/" version.go

      - name: Commit and Retag
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          # 配置 Git 身份
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # 创建新提交 (关键：在原有提交上新增)
          git add version.go
          git commit -m "Update version to $TAG_NAME"
          
          # 删除旧标签并重新打标签（强制覆盖）
          git tag -d $TAG_NAME || true  # 忽略本地删除失败
          git push origin :refs/tags/$TAG_NAME || true  # 删除远程旧标签
          git tag -a $TAG_NAME -m "Release $TAG_NAME"
          
          # 推送新标签（使用完整引用路径）
          git push origin refs/tags/$TAG_NAME --force

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}